#!/usr/bin/env python3
import os
import sys
import json
import urllib.request
import urllib.error
import re
import argparse
from pathlib import Path
from datetime import datetime

ROOT_DIR = Path("D:/Obsidian/My Wiki")
WIKI_DIR = ROOT_DIR / "wiki"
RAW_DIR = ROOT_DIR / "raw"
DRAFTS_DIR = ROOT_DIR / "drafts"
ENV_PATH = Path(__file__).resolve().parent.parent / ".env"

DRAFTS_DIR.mkdir(parents=True, exist_ok=True)

def load_env():
    env_vars = {}
    if ENV_PATH.exists():
        try:
            with open(ENV_PATH, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    if "=" in line:
                        k, v = line.split("=", 1)
                        env_vars[k.strip()] = v.strip()
        except Exception as e:
            print(f"[WARN] Failed to read .env: {e}")
    return env_vars

def call_llm(prompt, system_prompt, env_vars):
    api_key = env_vars.get("DEEPSEEK_API_KEY")
    api_url = env_vars.get("DEEPSEEK_API_URL", "https://api.deepseek.com").rstrip("/") + "/chat/completions"
    model = env_vars.get("DEEPSEEK_MODEL", "deepseek-chat")
    
    if not api_key:
        api_key = env_vars.get("MISTRAL_API_KEY")
        api_url = "https://api.mistral.ai/v1/chat/completions"
        model = env_vars.get("MISTRAL_MODEL", "mistral-tiny")
        
    if not api_key:
        raise ValueError("No API Key found for DeepSeek or Mistral. Set them in .env file.")

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3
    }

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(api_url, data=data, headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=45) as response:
            res_body = response.read().decode("utf-8")
            res_data = json.loads(res_body)
            return res_data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        err_msg = e.read().decode("utf-8")
        raise RuntimeError(f"API Error ({e.code}): {err_msg}")
    except Exception as e:
        raise RuntimeError(f"HTTP Connection failed: {e}")

def sanitize_filename(name):
    name = re.sub(r"[^\w\s-]", "", name)
    name = re.sub(r"\s+", "_", name)
    return name.lower().strip("_")

def make_fallback_drafts(file_path):
    # Generates a simple template note if no API key is available
    name = file_path.stem
    curr_date = datetime.now().strftime("%Y-%m-%d")
    
    summary_content = (
        f"<!-- target: wiki/summary_{name}.md -->\n"
        f"<!-- title: Summary of {name.replace('_', ' ').capitalize()} -->\n"
        f"---\n"
        f"type: summary\n"
        f"title: \"Summary of {name.replace('_', ' ').capitalize()}\"\n"
        f"description: \"Autogenerated placeholder summary for {file_path.name}\"\n"
        f"tags: [draft, autogenerated]\n"
        f"timestamp: {curr_date}\n"
        f"sources: [\"raw/{file_path.name}\"]\n"
        f"---\n\n"
        f"# Summary of {name.replace('_', ' ').capitalize()}\n\n"
        f"This is a placeholder draft note generated automatically because no AI API Keys are configured in your `.env` file.\n\n"
        f"Please fill in Mistral or DeepSeek API keys to activate full AI summarization and note drafting!\n"
    )
    
    draft_file = DRAFTS_DIR / f"summary_{name}.md"
    draft_file.write_text(summary_content, encoding="utf-8")
    print(f"Generated fallback draft: drafts/summary_{name}.md")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True, help="Path to raw source file")
    args = parser.parse_args()
    
    file_path = Path(args.file)
    if not file_path.exists():
        print(f"Error: File {args.file} not found.")
        sys.exit(1)
        
    env_vars = load_env()
    
    if not env_vars.get("DEEPSEEK_API_KEY") and not env_vars.get("MISTRAL_API_KEY"):
        print("[WARN] No Mistral or DeepSeek keys found. Generating fallback drafts...")
        make_fallback_drafts(file_path)
        sys.exit(0)
        
    try:
        raw_text = file_path.read_text(encoding="utf-8")
        
        system_prompt = (
            "You are an expert AI educational content writer.\n"
            "Your task is to analyze raw study materials and draft structured Wiki markdown files.\n"
            "You MUST output exactly two or three separated markdown note pages.\n"
            "Use the token 'FILE_START: target_relative_path' on a new line to separate the files. e.g.:\n"
            "FILE_START: wiki/summary_calculus.md\n"
            "(note contents here)\n"
            "FILE_START: wiki/derivative.md\n"
            "(note contents here)\n\n"
            "For each note, you MUST start with a YAML frontmatter block:\n"
            "---\n"
            "type: summary | concept | entity\n"
            "title: \"Clear Title\"\n"
            "description: \"One-sentence description\"\n"
            "tags: [tag1, tag2]\n"
            "timestamp: YYYY-MM-DD\n"
            "sources: [\"raw/filename.txt\"]\n"
            "---\n\n"
            "Guidelines:\n"
            "1. File 1 MUST be a summary note (e.g. wiki/summary_[topic].md).\n"
            "2. File 2 and 3 can be key concept notes (e.g. wiki/concept_name.md) or entities (e.g. wiki/newton.md) found in the text.\n"
            "3. Interlink notes using double brackets: [[concept_name]] or [[summary_topic]]."
        )
        
        prompt = (
            f"Analyze the following text and draft notes. The current date is {datetime.now().strftime('%Y-%m-%d')}.\n"
            f"Source file path is: raw/{file_path.name}\n\n"
            f"--- SOURCE TEXT ---\n"
            f"{raw_text[:8000]}\n"
        )
        
        print("Sending source text to AI for auto-drafting...")
        llm_response = call_llm(prompt, system_prompt, env_vars)
        
        # Parse the response and write files
        chunks = re.split(r"FILE_START:\s*", llm_response)
        
        drafts_written = 0
        for chunk in chunks:
            chunk = chunk.strip()
            if not chunk:
                continue
                
            # Split target path from content
            lines = chunk.split("\n")
            target_path_raw = lines[0].strip()
            content = "\n".join(lines[1:]).strip()
            
            # Extract target filename
            target_name = Path(target_path_raw).name
            if not target_name.endswith(".md"):
                continue
                
            # Extract YAML title
            title_match = re.search(r"title:\s*\"(.*?)\"", content)
            title = title_match.group(1) if title_match else target_name.replace(".md", "").replace("_", " ").capitalize()
            
            # Format drafts file with helper comments for the server
            draft_content = (
                f"<!-- target: wiki/{target_name} -->\n"
                f"<!-- title: {title} -->\n"
                f"{content}"
            )
            
            draft_path = DRAFTS_DIR / target_name
            draft_path.write_text(draft_content, encoding="utf-8")
            print(f"  - Generated draft: drafts/{target_name} (target: wiki/{target_name})")
            drafts_written += 1
            
        print(f"Successfully generated {drafts_written} drafts in drafts/ directory!")
        
    except Exception as e:
        print(f"[ERROR] Auto-ingestion failed: {e}")
        make_fallback_drafts(file_path)
        sys.exit(1)

if __name__ == "__main__":
    main()
